d /var/lib/walksafe/uploads 2750 walksafe-backend walksafe-backup-readers -
d /var/lib/walksafe/raw-objects 2750 walksafe-backend walksafe-backup-readers -
d /run/walksafe-maintenance-lock 0750 root walksafe-maintenance-lock -
f /run/walksafe-maintenance-lock/maintenance.lock 0440 root walksafe-maintenance-lock -
