#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ANDROID = ROOT / "apps" / "android"
REQUIRED_FILES = [
    "settings.gradle.kts",
    "build.gradle.kts",
    "app/build.gradle.kts",
    "gradlew",
    "gradlew.bat",
    "gradle/wrapper/gradle-wrapper.properties",
    "gradle/wrapper/gradle-wrapper.jar",
    "app/src/main/AndroidManifest.xml",
    "app/src/debug/AndroidManifest.xml",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/CameraBackgroundRenderer.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/DebugBboxOverlayView.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/MetadataCaptureLog.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/device/DeviceGate.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/feedback/AndroidFeedbackActuator.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/feedback/WalkSafeFeedbackPolicy.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/navigation/AndroidStepTracker.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/navigation/BackendWalkingRouteClient.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/navigation/LocationPolicy.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/navigation/RouteNavigator.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/navigation/StepLengthEstimator.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/navigation/WalkingRouteModels.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/report/AndroidReportCandidatePolicy.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/debuglog/MetadataLogJsonEncoder.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/debuglog/MetadataLogUploader.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/debuglog/MetadataLogEndpointPolicy.kt",
    "app/src/debug/java/kr/co/hanium/dreamup/walksafe/debuglog/DebugMetadataLogUploaderFactory.kt",
    "app/src/debug/java/kr/co/hanium/dreamup/walksafe/debuglog/HttpMetadataLogUploader.kt",
    "app/src/release/java/kr/co/hanium/dreamup/walksafe/debuglog/DebugMetadataLogUploaderFactory.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ArCoreFrameProvider.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthContracts.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthSampler.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/CoordinateMapper.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/MessagePolicy.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/MaskPolygonExtractor.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthGeometry.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ArCoreImageConverters.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthFrameSnapshot.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ObjectTracker.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthEstimator.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/TactilePathPolicy.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/TrackerRiskPolicy.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/AndroidDetectorContracts.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TwoModelClassMap.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TwoModelRuntimeConfig.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/YoloEndToEndOutputParser.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/YuvImagePreprocessor.kt",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TfliteAndroidFrameDetector.kt",
    "app/src/main/assets/model-config/two_model_runtime.json",
    "app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ObjectDepthRuntimePipeline.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/CoordinateMapperTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/DepthSamplerTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/MessagePolicyTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/DepthEstimatorTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/ObjectTrackerTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/DepthSmokePipelineTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/ObjectDepthRuntimePipelineTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/MetadataCaptureLogTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/debuglog/MetadataLogJsonEncoderTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/inference/YoloEndToEndOutputParserTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/inference/YuvImagePreprocessorTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/inference/TwoModelRuntimeConfigTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/device/DeviceGateTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/feedback/WalkSafeFeedbackPolicyTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/navigation/BackendWalkingRouteClientTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/navigation/LocationPolicyTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/navigation/RouteNavigatorTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/navigation/StepLengthEstimatorTest.kt",
    "app/src/test/java/kr/co/hanium/dreamup/walksafe/report/AndroidReportCandidatePolicyTest.kt",
]

CHECKS = [
    ("gradle/wrapper/gradle-wrapper.properties", "gradle-9.3.1-bin.zip"),
    ("build.gradle.kts", "com.android.application"),
    ("app/build.gradle.kts", "com.google.ar:core:1.54.0"),
    ("app/build.gradle.kts", "com.google.android.gms:play-services-location:21.3.0"),
    ("app/build.gradle.kts", "org.tensorflow:tensorflow-lite:2.17.0"),
    ("app/build.gradle.kts", "noCompress += \"tflite\""),
    ("app/build.gradle.kts", "compileSdk = 36"),
    ("app/src/main/AndroidManifest.xml", "android.permission.CAMERA"),
    ("app/src/main/AndroidManifest.xml", "android.permission.INTERNET"),
    ("app/src/main/AndroidManifest.xml", "android.permission.ACCESS_FINE_LOCATION"),
    ("app/src/main/AndroidManifest.xml", "android.permission.ACTIVITY_RECOGNITION"),
    ("app/src/main/AndroidManifest.xml", "android.permission.VIBRATE"),
    ("app/src/debug/AndroidManifest.xml", "android:usesCleartextTraffic=\"true\""),
    ("app/src/main/AndroidManifest.xml", "com.google.ar.core.depth"),
    ("app/src/main/AndroidManifest.xml", "android:value=\"optional\""),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/CameraBackgroundRenderer.kt", "samplerExternalOES"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/DebugBboxOverlayView.kt", "class DebugBboxOverlayView"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/DebugBboxOverlayView.kt", "canvas.drawRect"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "samples "),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MetadataCaptureLog.kt", "class MetadataCaptureLog"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MetadataCaptureLog.kt", "MetadataCaptureLogEntry"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MetadataCaptureLog.kt", "ArrayDeque"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MetadataCaptureLog.kt", "capture:"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MetadataCaptureLog.kt", "transformPath"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MetadataCaptureLog.kt", "fallbackReason"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MetadataCaptureLog.kt", "depthSize="),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "backgroundRenderer.draw(frame, cameraTextureId)"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "DebugBboxOverlayView"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "debugBboxOverlay.updateMapped("),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "MetadataCaptureLog"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "DebugMetadataLogUploaderFactory.create"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "metadataLogUploader.enqueue"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "서버 로그 켜기"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "buildCaptureLogEntry"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "transformPath = depthTransformPath"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "arcore_depth_mapper_unavailable"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "freshDetections("),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "MAX_DEPTH_DETECTION_SOURCE_AGE_MS"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "MAX_DEPTH_DETECTION_FRAME_DELTA_MS"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "staleReason("),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "captureLog.clear()"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "currentSession.setDisplayGeometry"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "checkAvailability(this)"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "UNSUPPORTED_DEVICE_NOT_CAPABLE"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "pendingSessionStartAfterInstall"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "ACTION_APPLICATION_DETAILS_SETTINGS"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "DETECTION_INTERVAL_MS"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "walksafe-tflite-detector"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "detectionInFlight"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "scheduleDetectionIfDue"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "acquireCameraImageOrNull(frame)"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "TfliteAndroidFrameDetector.createWithStatus"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "DeviceGateState"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "emitFeedbackAction(action)"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "tts=off_until_device_gate"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "loadDetectorAfterDepthGate()"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "LocationTrustPolicy.trustedOrNull"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "WalkingRouteRequest"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "AndroidReportCandidateInput"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/MainActivity.kt", "frameDetector.detect"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ArCoreFrameProvider.kt", "Config.DepthMode.AUTOMATIC"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ArCoreFrameProvider.kt", "acquireRawDepthImage16Bits"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ArCoreFrameProvider.kt", "acquireRawDepthConfidenceImage"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ArCoreFrameProvider.kt", "acquireDepthImage16Bits"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthSampler.kt", "pointInPolygon"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthSampler.kt", "outlierMadK"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthContracts.kt", "ARCORE_RAW_DEPTH"),

    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthContracts.kt", "trustedForStepGuidance"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthContracts.kt", "hardGate"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ArCoreFrameProvider.kt", "val fullDepth = tryAcquire"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ArCoreImageConverters.kt", "rowStride"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ArCoreImageConverters.kt", "pixelStride"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthFrameSnapshot.kt", "toSnapshotAndClose"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ObjectDepthRuntimePipeline.kt", "EmptyDetectionProvider"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/AndroidDetectorContracts.kt", "AndroidFrameDetector"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TwoModelClassMap.kt", "customTactileClasses"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TwoModelClassMap.kt", "cocoClassName"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/YoloEndToEndOutputParser.kt", "DEFAULT_ROWS = 300"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/YoloEndToEndOutputParser.kt", "DEFAULT_COLUMNS = 6"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/YuvImagePreprocessor.kt", "class YuvImagePreprocessor"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/YuvImagePreprocessor.kt", "fun modelRectToImageRect"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/YuvImagePreprocessor.kt", "ByteBuffer.allocateDirect"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TwoModelRuntimeConfig.kt", "model-config/two_model_runtime.json"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TwoModelRuntimeConfig.kt", "fun parse(json: String)"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TwoModelRuntimeConfig.kt", "thresholdForClass"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TfliteAndroidFrameDetector.kt", "org.tensorflow.lite.Interpreter"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TfliteAndroidFrameDetector.kt", "fun createOrNull(context: Context)"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TfliteAndroidFrameDetector.kt", "fun createWithStatus(context: Context)"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TfliteAndroidFrameDetector.kt", "setNumThreads"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TfliteAndroidFrameDetector.kt", "TwoModelRuntimeConfig.load(context)"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/inference/TfliteAndroidFrameDetector.kt", "modelRectToImageRect"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/debuglog/MetadataLogJsonEncoder.kt", "\"android.depth_debug.v1\""),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/debuglog/MetadataLogJsonEncoder.kt", "\"entries\""),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/debuglog/MetadataLogEndpointPolicy.kt", "setOf(\"http\", \"https\")"),
    ("app/src/debug/java/kr/co/hanium/dreamup/walksafe/debuglog/HttpMetadataLogUploader.kt", "HttpURLConnection"),
    ("app/src/debug/java/kr/co/hanium/dreamup/walksafe/debuglog/HttpMetadataLogUploader.kt", "MIN_UPLOAD_INTERVAL_MS = 2_000L"),
    ("app/src/release/java/kr/co/hanium/dreamup/walksafe/debuglog/DebugMetadataLogUploaderFactory.kt", "NoopMetadataLogUploader"),
    ("app/src/main/assets/model-config/two_model_runtime.json", "custom_tactile_yolo26s_float32.tflite"),
    ("app/src/main/assets/model-config/two_model_runtime.json", "coco_yolo26n_float32.tflite"),
    ("app/src/main/assets/model-config/two_model_runtime.json", "\"classes\""),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthSampler.kt", "confidenceMedian"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthSampler.kt", "erodePolygonTowardCentroid"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/CoordinateMapper.kt", "rotationDeg"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/CoordinateMapper.kt", "depthPixelToCameraPoint"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/MaskPolygonExtractor.kt", "bottomContactPoint"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ObjectTracker.kt", "idSwitchSuspected"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/ObjectTracker.kt", "timeToCollisionMs"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/TrackerRiskPolicy.kt", "TTC"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/TrackerRiskPolicy.kt", "IdSwitchSuspicionPolicy"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthEstimator.kt", "MIN_RAW_VALID_SAMPLES"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/DepthEstimator.kt", "POLYGON_TREND_PSEUDO_DEPTH"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/MessagePolicy.kt", "trustedForStepGuidance"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/MessagePolicy.kt", "PATH_GUIDANCE"),
    ("app/src/main/java/kr/co/hanium/dreamup/walksafe/depth/MessagePolicy.kt", "REPORT_ONLY"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/CoordinateMapperTest.kt", "modelToImageAppliesRotationAndMirrorInModelInputSpace"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/CoordinateMapperTest.kt", "imageToModelRoundTripsRotationAndMirrorCases"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/CoordinateMapperTest.kt", "270, -90"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/CoordinateMapperTest.kt", "mirrored = true"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/MessagePolicyTest.kt", "normalTactileBlockWithUntrustedMetricSourceKeepsGenericPathGuidanceWithoutSteps"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/MessagePolicyTest.kt", "trustedForStepGuidance"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/DepthSmokePipelineTest.kt", "sampleCenterPrefersRawDepthAndFormatsSummary"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/DepthSmokePipelineTest.kt", "sampleCenterFallsBackToFullDepthWhenRawConfidenceIsRejected"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/DepthSmokePipelineTest.kt", "summaryTextUsesNoDistanceWhenMedianIsMissing"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/ObjectDepthRuntimePipelineTest.kt", "runtimePipelineConnectsDetectionTrackerAndRawDepthEstimator"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/depth/ObjectDepthRuntimePipelineTest.kt", "POLYGON_TREND_PSEUDO_DEPTH"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/inference/YoloEndToEndOutputParserTest.kt", "parserConvertsPixelXyxyRowsToDetectionCandidates"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/inference/YuvImagePreprocessorTest.kt", "modelRectToImageRectRemovesVerticalLetterboxPaddingForLandscapeImage"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/inference/TwoModelRuntimeConfigTest.kt", "parsesAndroidAssetConfigAsRuntimeSourceOfTruth"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/MetadataCaptureLogTest.kt", "summaryMarksSuppressedStaleDetectionsWithoutImageFields"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/MetadataCaptureLogTest.kt", "transform=identity"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/debuglog/MetadataLogJsonEncoderTest.kt", "assertFalse(encoded.contains(\"gps\"))"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/MetadataCaptureLogTest.kt", "clearRemovesSessionLocalMetadata"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/device/DeviceGateTest.kt", "startupReadyAllowsActuatorsButRiskAlertsStillNeedFreshDepthObject"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/feedback/WalkSafeFeedbackPolicyTest.kt", "blocksAlertsBeforeDeviceGatePass"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/navigation/BackendWalkingRouteClientTest.kt", "postsToBackendWalkingProxyWithoutTmapKey"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/navigation/LocationPolicyTest.kt", "rejectsNullOrPoorAccuracyForRouteDecisions"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/navigation/RouteNavigatorTest.kt", "gatesRerouteByOffRouteCooldownAndInFlight"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/navigation/StepLengthEstimatorTest.kt", "acceptsOnlyValidCalibrationRange"),
    ("app/src/test/java/kr/co/hanium/dreamup/walksafe/report/AndroidReportCandidatePolicyTest.kt", "preparesOnlyAndroidDamageCandidateWithGpsAndAllowedModel"),
]


def fail(message: str) -> None:
    raise SystemExit(f"FAIL: {message}")


def main() -> None:
    for rel in REQUIRED_FILES:
        path = ANDROID / rel
        if not path.exists():
            fail(f"missing {path}")
    for rel, needle in CHECKS:
        text = (ANDROID / rel).read_text(encoding="utf-8")
        if needle not in text:
            fail(f"{needle!r} not found in {rel}")
    source_text = "\n".join(path.read_text(encoding="utf-8") for path in (ANDROID / "app/src/main/java").rglob("*.kt"))
    if "SharedCamera" in source_text:
        fail("SharedCamera must not be used in depth-critical path")
    debug_manifest = (ANDROID / "app/src/debug/AndroidManifest.xml").read_text(encoding="utf-8")
    if "android:usesCleartextTraffic=\"true\"" not in debug_manifest:
        fail("cleartext HTTP must stay debug-only")
    build_text = (ANDROID / "build.gradle.kts").read_text(encoding="utf-8") + "\n" + (ANDROID / "app/build.gradle.kts").read_text(encoding="utf-8")
    if "org.jetbrains.kotlin.android" in build_text:
        fail("AGP 9 has built-in Kotlin support; do not apply org.jetbrains.kotlin.android")
    print("PASS: android ARCore depth scaffold static checks passed")


if __name__ == "__main__":
    main()
