#!/bin/bash -p
set -euo pipefail
umask 077
export PATH=/usr/bin:/bin
unset BASH_ENV ENV CDPATH GLOBIGNORE TAR_OPTIONS PYTHONPATH PYTHONHOME PYTHONSTARTUP
unset PGHOST PGHOSTADDR PGPORT PGDATABASE PGUSER PGPASSWORD PGPASSFILE PGSERVICE PGSERVICEFILE
unset PGOPTIONS PGAPPNAME PGSSLMODE PGREQUIRESSL PGSSLCOMPRESSION PGSSLCERT PGSSLKEY
unset PGSSLROOTCERT PGSSLCRL PGSSLCRLDIR PGGSSENCMODE PGCHANNELBINDING PGTARGETSESSIONATTRS
for AMBIENT_PG_NAME in "${!PG@}"; do
  unset "${AMBIENT_PG_NAME}"
done
unset AMBIENT_PG_NAME
[[ "$-" == *p* ]] || {
  echo '{"verified":false,"status":"PRIVILEGED_SHELL_REQUIRED"}' >&2
  exit 2
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_SCRIPT="${SCRIPT_DIR}/backup_walksafe_data_20260711.sh"
INTEGRITY_SCRIPT="${SCRIPT_DIR}/walksafe_backup_integrity.py"
BACKUP_RUNTIME_PYTHON="/usr/bin/python3.14"
QUIESCE_APPROVAL_MARKER="/etc/walksafe/backup-writes-quiesced.approved"
QUIESCE_APPROVAL_MAX_AGE_SECONDS=300

fail_closed() {
  local status="$1"
  printf '{"verified":false,"status":"%s"}\n' "${status}" >&2
  exit 2
}

[[ -f "${QUIESCE_APPROVAL_MARKER}" && ! -L "${QUIESCE_APPROVAL_MARKER}" \
  && "$(realpath "${QUIESCE_APPROVAL_MARKER}")" == "${QUIESCE_APPROVAL_MARKER}" \
  && "$(stat -Lc '%u:%g:%a:%h:%s' "${QUIESCE_APPROVAL_MARKER}")" == "0:$(id -g):440:1:16" \
  && "$(<"${QUIESCE_APPROVAL_MARKER}")" == "WRITES-QUIESCED" ]] \
  || fail_closed "QUIESCE_APPROVAL_REQUIRED"
MARKER_MTIME="$(stat -Lc '%Y' "${QUIESCE_APPROVAL_MARKER}")"
CURRENT_TIME="$(date +%s)"
[[ "${MARKER_MTIME}" =~ ^[0-9]+$ && "${CURRENT_TIME}" =~ ^[0-9]+$ \
  && "${MARKER_MTIME}" -le "${CURRENT_TIME}" \
  && $((CURRENT_TIME - MARKER_MTIME)) -le "${QUIESCE_APPROVAL_MAX_AGE_SECONDS}" ]] \
  || fail_closed "QUIESCE_APPROVAL_STALE"

REQUIRED_ENVIRONMENT=(
  DATABASE_URL
  UPLOAD_DIR
  GNUPGHOME
  WALKSAFE_BACKUP_OUTPUT_DIR
  WALKSAFE_BACKUP_GPG_RECIPIENT
  WALKSAFE_BACKUP_GPG_SIGNER
  WALKSAFE_BACKUP_TRUSTED_SIGNER_FINGERPRINT
  WALKSAFE_BACKUP_KEY_CONTROL_DOCUMENT
  WALKSAFE_BACKUP_KEY_CONTROL_SIGNATURE
  WALKSAFE_BACKUP_KEY_CONTROL_AUTHORITY_LOCK
  WALKSAFE_BACKUP_KEY_CONTROL_TRUSTED_SIGNER_FINGERPRINT
  WALKSAFE_BACKUP_KEY_CONTROL_HEAD_SHA256
  WALKSAFE_MAINTENANCE_LOCK_PATH
  WALKSAFE_MAINTENANCE_LOCK_GROUP
  WALKSAFE_UPLOAD_BACKUP_READER_GROUP
  WALKSAFE_MAINTENANCE_LOCK_TIMEOUT_SECONDS
  WALKSAFE_BACKEND_PYTHON
  WALKSAFE_BACKUP_ACTOR_ID
  WALKSAFE_BACKUP_MAX_AGE_SECONDS
  WALKSAFE_BACKUP_FUTURE_SKEW_SECONDS
)
for ENVIRONMENT_NAME in "${REQUIRED_ENVIRONMENT[@]}"; do
  ENVIRONMENT_VALUE="${!ENVIRONMENT_NAME:-}"
  [[ -n "${ENVIRONMENT_VALUE}" && "${ENVIRONMENT_VALUE}" != *CHANGE_ME* ]] \
    || fail_closed "BACKUP_CONFIGURATION_INVALID"
done
unset ENVIRONMENT_NAME ENVIRONMENT_VALUE

[[ "${WALKSAFE_BACKUP_GPG_RECIPIENT}" =~ ^[A-Fa-f0-9]{40}$ \
  && "${WALKSAFE_BACKUP_GPG_SIGNER}" =~ ^[A-Fa-f0-9]{40}$ \
  && "${WALKSAFE_BACKUP_TRUSTED_SIGNER_FINGERPRINT}" =~ ^[A-Fa-f0-9]{40}$ \
  && "${WALKSAFE_BACKUP_GPG_SIGNER,,}" == "${WALKSAFE_BACKUP_TRUSTED_SIGNER_FINGERPRINT,,}" \
  && "${WALKSAFE_BACKUP_KEY_CONTROL_TRUSTED_SIGNER_FINGERPRINT}" =~ ^[A-Fa-f0-9]{40}$ \
  && "${WALKSAFE_BACKUP_KEY_CONTROL_HEAD_SHA256}" =~ ^[a-f0-9]{64}$ ]] \
  || fail_closed "BACKUP_CONFIGURATION_INVALID"
[[ "${WALKSAFE_BACKUP_MAX_AGE_SECONDS}" =~ ^[0-9]+$ \
  && "${WALKSAFE_BACKUP_MAX_AGE_SECONDS}" -ge 1 \
  && "${WALKSAFE_BACKUP_MAX_AGE_SECONDS}" -le 3024000 \
  && "${WALKSAFE_BACKUP_FUTURE_SKEW_SECONDS}" =~ ^[0-9]+$ \
  && "${WALKSAFE_BACKUP_FUTURE_SKEW_SECONDS}" -le 3600 ]] \
  || fail_closed "BACKUP_CONFIGURATION_INVALID"
[[ "${WALKSAFE_BACKUP_ACTOR_ID}" =~ ^[A-Za-z0-9][A-Za-z0-9._@-]{0,63}$ ]] \
  || fail_closed "BACKUP_CONFIGURATION_INVALID"
for ABSOLUTE_PATH in \
  "${UPLOAD_DIR}" \
  "${GNUPGHOME}" \
  "${WALKSAFE_BACKUP_OUTPUT_DIR}" \
  "${WALKSAFE_BACKUP_KEY_CONTROL_DOCUMENT}" \
  "${WALKSAFE_BACKUP_KEY_CONTROL_SIGNATURE}" \
  "${WALKSAFE_BACKUP_KEY_CONTROL_AUTHORITY_LOCK}" \
  "${WALKSAFE_MAINTENANCE_LOCK_PATH}" \
  "${WALKSAFE_BACKEND_PYTHON}"; do
  [[ "${ABSOLUTE_PATH}" == /* ]] || fail_closed "BACKUP_CONFIGURATION_INVALID"
done
unset ABSOLUTE_PATH

BACKUP_ARGUMENTS=(
  --output-dir "${WALKSAFE_BACKUP_OUTPUT_DIR}"
  --upload-dir "${UPLOAD_DIR}"
  --actor-id "${WALKSAFE_BACKUP_ACTOR_ID}"
  --gpg-recipient "${WALKSAFE_BACKUP_GPG_RECIPIENT}"
  --gpg-signer "${WALKSAFE_BACKUP_GPG_SIGNER}"
  --key-control-document "${WALKSAFE_BACKUP_KEY_CONTROL_DOCUMENT}"
  --key-control-signature "${WALKSAFE_BACKUP_KEY_CONTROL_SIGNATURE}"
  --key-control-authority-lock "${WALKSAFE_BACKUP_KEY_CONTROL_AUTHORITY_LOCK}"
  --trusted-key-control-signer-fingerprint "${WALKSAFE_BACKUP_KEY_CONTROL_TRUSTED_SIGNER_FINGERPRINT}"
  --expected-key-control-sha256 "${WALKSAFE_BACKUP_KEY_CONTROL_HEAD_SHA256}"
  --maintenance-lock "${WALKSAFE_MAINTENANCE_LOCK_PATH}"
  --confirm-quiesced WRITES-QUIESCED
)
if ! BACKUP_OUTPUT="$({
  DATABASE_URL="${DATABASE_URL}" \
  UPLOAD_DIR="${UPLOAD_DIR}" \
  GNUPGHOME="${GNUPGHOME}" \
  WALKSAFE_BACKEND_PYTHON="${WALKSAFE_BACKEND_PYTHON}" \
  WALKSAFE_MAINTENANCE_LOCK_GROUP="${WALKSAFE_MAINTENANCE_LOCK_GROUP}" \
  WALKSAFE_UPLOAD_BACKUP_READER_GROUP="${WALKSAFE_UPLOAD_BACKUP_READER_GROUP}" \
  WALKSAFE_MAINTENANCE_LOCK_TIMEOUT_SECONDS="${WALKSAFE_MAINTENANCE_LOCK_TIMEOUT_SECONDS}" \
    "${BACKUP_SCRIPT}" "${BACKUP_ARGUMENTS[@]}"
} 2>/dev/null)"; then
  fail_closed "BACKUP_CREATION_FAILED"
fi
[[ "${BACKUP_OUTPUT}" == backup_dir=* && "${BACKUP_OUTPUT}" != *$'\n'* ]] \
  || fail_closed "BACKUP_RESULT_INVALID"
BACKUP_DIR_PATH="${BACKUP_OUTPUT#backup_dir=}"
OUTPUT_ROOT_REAL="$(realpath "${WALKSAFE_BACKUP_OUTPUT_DIR}")"
BACKUP_DIR_REAL="$(realpath "${BACKUP_DIR_PATH}")"
[[ "${BACKUP_DIR_PATH}" == "${BACKUP_DIR_REAL}" \
  && "${BACKUP_DIR_REAL}" == "${OUTPUT_ROOT_REAL}"/walksafe-backup-* \
  && "$(stat -Lc '%u:%a' "${BACKUP_DIR_REAL}")" == "$(id -u):700" ]] \
  || fail_closed "BACKUP_RESULT_INVALID"
for ARTIFACT_NAME in manifest.json manifest.json.sig reports.dump.gpg uploads.tar.gz.gpg; do
  [[ -f "${BACKUP_DIR_REAL}/${ARTIFACT_NAME}" && ! -L "${BACKUP_DIR_REAL}/${ARTIFACT_NAME}" \
    && "$(stat -Lc '%u:%a:%h' "${BACKUP_DIR_REAL}/${ARTIFACT_NAME}")" == "$(id -u):600:1" ]] \
    || fail_closed "BACKUP_RESULT_INVALID"
done
unset ARTIFACT_NAME

if ! VERIFICATION_OUTPUT="$({
  "${BACKUP_RUNTIME_PYTHON}" -I -S -B "${INTEGRITY_SCRIPT}" \
    --manifest "${BACKUP_DIR_REAL}/manifest.json" \
    --signature "${BACKUP_DIR_REAL}/manifest.json.sig" \
    --trusted-signer-fingerprint "${WALKSAFE_BACKUP_TRUSTED_SIGNER_FINGERPRINT}" \
    --max-age-seconds "${WALKSAFE_BACKUP_MAX_AGE_SECONDS}" \
    --future-skew-seconds "${WALKSAFE_BACKUP_FUTURE_SKEW_SECONDS}"
} 2>/dev/null)"; then
  fail_closed "BACKUP_VERIFICATION_FAILED"
fi
printf '%s\n' "${VERIFICATION_OUTPUT}"
